## 导入包

In [3]:
import torch
import numpy

## 创建数组
形状
数据类型
值

In [22]:
x = torch.arange(0, 12)
print(x)
print(x.shape)
print(x.numel())
y = torch.zeros((2, 3))
z = torch.ones((2, 3))
X = x.reshape(3, 4)
print(X)
print(y)
print(z)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
x = torch.tensor([[1, 2, 3],[3, 4, 5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

## 访问元素


In [18]:
x[1:2, 1:]

tensor([[4, 5]])

## 运算

In [27]:
print(x + z)
print(x - z)
print(x * y)
print(x / x)
print(x ** x)
torch.exp(x)

tensor([[2., 3., 4.],
        [4., 5., 6.]])
tensor([[0., 1., 2.],
        [2., 3., 4.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[   1,    4,   27],
        [  27,  256, 3125]])


tensor([[  2.7183,   7.3891,  20.0855],
        [ 20.0855,  54.5981, 148.4132]])

In [33]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.zeros((3, 4))
print(torch.cat((X, Y), dim=0))
print(torch.cat((X, Y), dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])
tensor([[ 0.,  1.,  2.,  3.,  0.,  0.,  0.,  0.],
        [ 4.,  5.,  6.,  7.,  0.,  0.,  0.,  0.],
        [ 8.,  9., 10., 11.,  0.,  0.,  0.,  0.]])


In [34]:
X == Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [35]:
X.sum()

tensor(66.)

## 广播机制
对两个形状不同的张量进行运算，会复制为形状相同的两个张量再运算

In [37]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
print(a)
print(b)
a + b

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 内存开销

In [56]:
Z = X = torch.zeros((2, 3))
Y = torch.ones((2, 3))
print(id(X))
print(id(Z))

Z = X + Y
print(id(Z))
Z[:] = X + Y
print(id(Z))

print(id(X))
Z = X.reshape(3, 2)
print(id(Z))
Z[:] = -1
print(X)

140236530037488
140236530037488
140236531479088
140236531479088
140236530037488
140236531478704
tensor([[-1., -1., -1.],
        [-1., -1., -1.]])


## numpy

In [50]:
A = X.numpy()
B = torch.tensor(A)
print(type(A))
print(type(B))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [52]:
a = torch.tensor([3.5])
type(a), type(a.item())

(torch.Tensor, float)