## 你可以将向量视为标量值组成的列表

In [2]:
import torch

In [3]:
x = torch.randn((4,))
x

tensor([-0.2103,  0.3444,  0.2444,  0.0700])

## 通过指定两个分量m和n来创建一个形状为mxn的矩阵

In [13]:
X = torch.randn((3, 4))
print(X)
print(X.T)
print(X[0][0].dtype)

tensor([[-0.2712,  0.4759,  0.0083,  0.0977],
        [-0.2603, -0.2380, -0.1181,  1.5081],
        [ 0.0936,  0.9325,  0.1837,  0.6670]])
tensor([[-0.2712, -0.2603,  0.0936],
        [ 0.4759, -0.2380,  0.9325],
        [ 0.0083, -0.1181,  0.1837],
        [ 0.0977,  1.5081,  0.6670]])
torch.float32


## 给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [16]:
x = torch.ones((2, 3))
y = x.clone()
print(x + y)
print(x * y)  # 两个矩阵的按元素乘法称为哈达玛积（Hadamard product）,数学符号⊙
print(x + 2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])


## 计算其元素的和、均值

In [39]:
x = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
print(x, x.shape)
print(x.sum(), x.sum().shape)
print(x.sum(axis=0), x.sum(axis=0).shape)
print(x.sum(axis=1), x.sum(axis=1).shape)
print(x.sum(axis=2), x.sum(axis=2).shape)
print(x / x.sum(axis=0, keepdim=True))
print(x.cumsum(axis=0))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]]) torch.Size([2, 3, 4])
tensor(276.) torch.Size([])
tensor([[12., 14., 16., 18.],
        [20., 22., 24., 26.],
        [28., 30., 32., 34.]]) torch.Size([3, 4])
tensor([[12., 15., 18., 21.],
        [48., 51., 54., 57.]]) torch.Size([2, 4])
tensor([[ 6., 22., 38.],
        [54., 70., 86.]]) torch.Size([2, 3])
tensor([[[0.0000, 0.0714, 0.1250, 0.1667],
         [0.2000, 0.2273, 0.2500, 0.2692],
         [0.2857, 0.3000, 0.3125, 0.3235]],

        [[1.0000, 0.9286, 0.8750, 0.8333],
         [0.8000, 0.7727, 0.7500, 0.7308],
         [0.7143, 0.7000, 0.6875, 0.6765]]])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]])


In [36]:
x = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
print(x)
print(x.mean())
print(x.mean(axis=0))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
tensor(11.5000)
tensor([[ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.]])
tensor([[[0.0000, 0.0714, 0.1250, 0.1667],
         [0.2000, 0.2273, 0.2500, 0.2692],
         [0.2857, 0.3000, 0.3125, 0.3235]],

        [[1.0000, 0.9286, 0.8750, 0.8333],
         [0.8000, 0.7727, 0.7500, 0.7308],
         [0.7143, 0.7000, 0.6875, 0.6765]]])


## 点积是相同位置的按元素乘积的和

In [45]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4)
torch.dot(x, y) == torch.sum(x * y)

tensor(True)

## 矩阵向量积与矩阵乘法

In [47]:
A = torch.randn((3, 4))
x = torch.ones(4, dtype=torch.float32)
print(torch.mv(A, x))

tensor([-3.5781,  1.4247,  0.0386])


In [48]:
A = torch.randn((3, 4))
B = torch.ones((4, 5), dtype=torch.float32)
print(torch.mm(A, B))

tensor([[ 0.3242,  0.3242,  0.3242,  0.3242,  0.3242],
        [ 1.5266,  1.5266,  1.5266,  1.5266,  1.5266],
        [-3.0302, -3.0302, -3.0302, -3.0302, -3.0302]])


## 向量的L2范数与矩阵的Frobenius范数

In [55]:
x = torch.arange(12, dtype=torch.float32)
print(torch.norm(x))
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print(torch.norm(X))

tensor(22.4944)
tensor(22.4944)
